# -*- coding: utf-8 -*-

"""
@file saison_4.py
@brief Fichier de définition de la classe Ui_saison_4
"""

# Form implementation generated from reading ui file './ressource/saison4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MAIN import main
from POPUP import BottomPopup
import ressources


class Ui_saison_4(object):
        """
        @class Ui_saison_4
        @brief Classe définissant l'interface utilisateur de la saison 4
        """

        def setupUi(self, saison_4):
                """
                @brief Configure l'interface utilisateur de la saison 4.

                @param saison_4 Le widget principal de l'interface.
                @type saison_4 QtWidgets.QWidget
                """

                self.ratioHeight = main.ratio_size(1080, 1)
                self.ratioWidth = main.ratio_size(1920, 0)

                saison_4.setObjectName("saison_4")
                saison_4.resize(1920, 1080)
                saison_4.setStyleSheet("QWidget#saison_4{\n"
                "    background-image: url(:/img/fond/printemps.png);\n"
                "    background-repeat: no-repeat;\n"
                "    background-position: center;\n"
                "    background-attachment: fixed;\n"
                "    background-size: cover;\n"
                "}\n"
                "QPushButton{\n"
                "    background-color: red;\n"
                "}\n"
                "\n"
                "QPushButton#sais_suiv{\n"
                "    background-color: grey;\n"
                "}\n"
                "QPushButton#sais_prec{\n"
                "    background-color: grey;\n"
                "}\n"
                "QPushButton#save{\n"
                "    background-color: grey;\n"
                "}\n"
                "QPushButton#quit{\n"
                "    background-color: grey;\n"
                "}")
                fontButtonNiv = QtGui.QFont()
                fontButtonNiv.setPointSize(15)

                fontButtonMenu = QtGui.QFont()
                fontButtonMenu.setPointSize(10)

                self.nbr_etoile = QtWidgets.QLabel(saison_4)
                self.nbr_etoile.setGeometry(main.creatRect(100, 70, 121, 61,self.ratioWidth,self.ratioHeight))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.nbr_etoile.setFont(font)
                self.nbr_etoile.setObjectName("nbr_etoile")

                self.e_3_4 = QtWidgets.QLabel(saison_4)
                self.e_3_4.setGeometry(main.creatRect(941, 30, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_3_4.setText("")
                self.e_3_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_4.setObjectName("e_3_4")
                self.e_5_3 = QtWidgets.QLabel(saison_4)
                self.e_5_3.setGeometry(main.creatRect(1099, 460, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_5_3.setText("")
                self.e_5_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_3.setObjectName("e_5_3")
                self.e_3_1 = QtWidgets.QLabel(saison_4)
                self.e_3_1.setGeometry(main.creatRect(788, 30, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_3_1.setText("")
                self.e_3_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_1.setObjectName("e_3_1")

                self.quit = QtWidgets.QPushButton(saison_4)
                self.quit.setGeometry(main.creatRect(1770, 1010, 121, 41,self.ratioWidth,self.ratioHeight))
                self.quit.setObjectName("quit")
                self.quit.setFont(fontButtonMenu)

                self.niv_5 = QtWidgets.QPushButton(saison_4)
                self.niv_5.setGeometry(main.creatRect(1078, 520, 101, 61,self.ratioWidth,self.ratioHeight))
                self.niv_5.setObjectName("niv_5")
                self.niv_5.setFont(fontButtonNiv)

                self.e_5_2 = QtWidgets.QLabel(saison_4)
                self.e_5_2.setGeometry(main.creatRect(1048, 460, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_5_2.setText("")
                self.e_5_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_2.setObjectName("e_5_2")
                self.nbr_e_img = QtWidgets.QLabel(saison_4)
                self.nbr_e_img.setGeometry(main.creatRect(40, 70, 51, 51,self.ratioWidth,self.ratioHeight))
                self.nbr_e_img.setText("")
                self.nbr_e_img.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.nbr_e_img.setObjectName("nbr_e_img")
                self.e_1_4 = QtWidgets.QLabel(saison_4)
                self.e_1_4.setGeometry(main.creatRect(513, 780, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_1_4.setText("")
                self.e_1_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_4.setObjectName("e_1_4")
                self.e_4_2 = QtWidgets.QLabel(saison_4)
                self.e_4_2.setGeometry(main.creatRect(1308, 170, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_4_2.setText("")
                self.e_4_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_2.setObjectName("e_4_2")
                self.e_3_5 = QtWidgets.QLabel(saison_4)
                self.e_3_5.setGeometry(main.creatRect(992, 30, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_3_5.setText("")
                self.e_3_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_5.setObjectName("e_3_5")
                self.nom_joueur = QtWidgets.QLabel(saison_4)
                self.nom_joueur.setGeometry(main.creatRect(20, 10, 371, 81,self.ratioWidth,self.ratioHeight))
                font = QtGui.QFont()
                font.setPointSize(30)
                self.nom_joueur.setFont(font)
                self.nom_joueur.setObjectName("nom_joueur")
                self.e_1_3 = QtWidgets.QLabel(saison_4)
                self.e_1_3.setGeometry(main.creatRect(462, 780, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_1_3.setText("")
                self.e_1_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_3.setObjectName("e_1_3")
                self.e_2_2 = QtWidgets.QLabel(saison_4)
                self.e_2_2.setGeometry(main.creatRect(501, 390, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_2_2.setText("")
                self.e_2_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_2.setObjectName("e_2_2")
                self.niv_4 = QtWidgets.QPushButton(saison_4)
                self.niv_4.setEnabled(True)
                self.niv_4.setGeometry(main.creatRect(1338, 230, 101, 61,self.ratioWidth,self.ratioHeight))
                self.niv_4.setObjectName("niv_4")
                self.niv_4.setFont(fontButtonNiv)
                self.e_2_3 = QtWidgets.QLabel(saison_4)
                self.e_2_3.setGeometry(main.creatRect(552, 390, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_2_3.setText("")
                self.e_2_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_3.setObjectName("e_2_3")
                self.e_4_1 = QtWidgets.QLabel(saison_4)
                self.e_4_1.setGeometry(main.creatRect(1257, 170, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_4_1.setText("")
                self.e_4_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_1.setObjectName("e_4_1")
                self.save = QtWidgets.QPushButton(saison_4)
                self.save.setGeometry(main.creatRect(1620, 1010, 121, 41,self.ratioWidth,self.ratioHeight))
                self.save.setObjectName("save")
                self.save.setFont(fontButtonMenu)
                self.e_3_2 = QtWidgets.QLabel(saison_4)
                self.e_3_2.setGeometry(main.creatRect(839, 30, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_3_2.setText("")
                self.e_3_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_2.setObjectName("e_3_2")
                self.niv_3 = QtWidgets.QPushButton(saison_4)
                self.niv_3.setGeometry(main.creatRect(869, 90, 101, 61,self.ratioWidth,self.ratioHeight))
                self.niv_3.setObjectName("niv_3")
                self.niv_3.setFont(fontButtonNiv)
                self.e_4_5 = QtWidgets.QLabel(saison_4)
                self.e_4_5.setGeometry(main.creatRect(1461, 170, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_4_5.setText("")
                self.e_4_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_5.setObjectName("e_4_5")
                self.e_2_5 = QtWidgets.QLabel(saison_4)
                self.e_2_5.setGeometry(main.creatRect(654, 390, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_2_5.setText("")
                self.e_2_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_5.setObjectName("e_2_5")
                self.niv_2 = QtWidgets.QPushButton(saison_4)
                self.niv_2.setGeometry(main.creatRect(524, 450, 101, 61,self.ratioWidth,self.ratioHeight))
                self.niv_2.setObjectName("niv_2")
                self.niv_2.setFont(fontButtonNiv)
                self.e_5_1 = QtWidgets.QLabel(saison_4)
                self.e_5_1.setGeometry(main.creatRect(997, 460, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_5_1.setText("")
                self.e_5_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_1.setObjectName("e_5_1")
                self.e_2_4 = QtWidgets.QLabel(saison_4)
                self.e_2_4.setGeometry(main.creatRect(603, 390, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_2_4.setText("")
                self.e_2_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_4.setObjectName("e_2_4")
                self.e_4_3 = QtWidgets.QLabel(saison_4)
                self.e_4_3.setGeometry(main.creatRect(1359, 170, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_4_3.setText("")
                self.e_4_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_3.setObjectName("e_4_3")
                self.e_2_1 = QtWidgets.QLabel(saison_4)
                self.e_2_1.setGeometry(main.creatRect(450, 390, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_2_1.setText("")
                self.e_2_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_1.setObjectName("e_2_1")
                self.sais_prec = QtWidgets.QPushButton(saison_4)
                self.sais_prec.setGeometry(main.creatRect(630, 1015, 141, 41,self.ratioWidth,self.ratioHeight))
                self.sais_prec.setObjectName("sais_prec")
                self.sais_prec.setFont(fontButtonMenu)
                self.e_5_5 = QtWidgets.QLabel(saison_4)
                self.e_5_5.setGeometry(main.creatRect(1201, 460, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_5_5.setText("")
                self.e_5_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_5.setObjectName("e_5_5")
                self.e_3_3 = QtWidgets.QLabel(saison_4)
                self.e_3_3.setGeometry(main.creatRect(890, 30, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_3_3.setText("")
                self.e_3_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_3.setObjectName("e_3_3")
                self.e_4_4 = QtWidgets.QLabel(saison_4)
                self.e_4_4.setGeometry(main.creatRect(1410, 170, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_4_4.setText("")
                self.e_4_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_4.setObjectName("e_4_4")
                self.e_1_2 = QtWidgets.QLabel(saison_4)
                self.e_1_2.setGeometry(main.creatRect(411, 780, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_1_2.setText("")
                self.e_1_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_2.setObjectName("e_1_2")
                self.e_1_5 = QtWidgets.QLabel(saison_4)
                self.e_1_5.setGeometry(main.creatRect(564, 780, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_1_5.setText("")
                self.e_1_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_5.setObjectName("e_1_5")
                self.niv_1 = QtWidgets.QPushButton(saison_4)
                self.niv_1.setGeometry(main.creatRect(433, 840, 101, 61,self.ratioWidth,self.ratioHeight))
                self.niv_1.setObjectName("niv_1")
                self.niv_1.setFont(fontButtonNiv)
                self.e_5_4 = QtWidgets.QLabel(saison_4)
                self.e_5_4.setGeometry(main.creatRect(1150, 460, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_5_4.setText("")
                self.e_5_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_4.setObjectName("e_5_4")
                self.label = QtWidgets.QLabel(saison_4)
                self.label.setGeometry(main.creatRect(1130, 780, 151, 121,self.ratioWidth,self.ratioHeight))
                self.label.setText("")
                self.label.setPixmap(QtGui.QPixmap(":/img/perso/petit-helper.png"))
                self.label.setObjectName("label")
                self.label.setToolTip("Indice")
                # Connecter le clic sur l'image à la fonction pour afficher la bulle de discussion
                self.label.mousePressEvent = self.showHintBubble
                self.e_1_1 = QtWidgets.QLabel(saison_4)
                self.e_1_1.setGeometry(main.creatRect(360, 780, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_1_1.setText("")
                self.e_1_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_1.setObjectName("e_1_1")

                self.retranslateUi(saison_4)
                QtCore.QMetaObject.connectSlotsByName(saison_4)

                self.widget = saison_4

                self.button_niv = []
                self.button_niv.append(self.niv_1)
                self.button_niv.append(self.niv_2)
                self.button_niv.append(self.niv_3)
                self.button_niv.append(self.niv_4)
                self.button_niv.append(self.niv_5)

                self.etoile_1 = []
                self.etoile_1.append(self.e_1_1)
                self.etoile_1.append(self.e_1_2)
                self.etoile_1.append(self.e_1_3)
                self.etoile_1.append(self.e_1_4)
                self.etoile_1.append(self.e_1_5)

                self.etoile_2 = []
                self.etoile_2.append(self.e_2_1)
                self.etoile_2.append(self.e_2_2)
                self.etoile_2.append(self.e_2_3)
                self.etoile_2.append(self.e_2_4)
                self.etoile_2.append(self.e_2_5)

                self.etoile_3 = []
                self.etoile_3.append(self.e_3_1)
                self.etoile_3.append(self.e_3_2)
                self.etoile_3.append(self.e_3_3)
                self.etoile_3.append(self.e_3_4)
                self.etoile_3.append(self.e_3_5)

                self.etoile_4 = []
                self.etoile_4.append(self.e_4_1)
                self.etoile_4.append(self.e_4_2)
                self.etoile_4.append(self.e_4_3)
                self.etoile_4.append(self.e_4_4)
                self.etoile_4.append(self.e_4_5)

                self.etoile_5 = []
                self.etoile_5.append(self.e_5_1)
                self.etoile_5.append(self.e_5_2)
                self.etoile_5.append(self.e_5_3)
                self.etoile_5.append(self.e_5_4)
                self.etoile_5.append(self.e_5_5)

                self.grpEtoile = self.griserEtoiles()

        def retranslateUi(self, saison_4):
                """
                @brief Retraduit les éléments de l'interface utilisateur.

                @param saison_4 Le widget principal de l'interface.
                @type saison_4 QtWidgets.QWidget
                """
                _translate = QtCore.QCoreApplication.translate
                saison_4.setWindowTitle(_translate("saison_4", "Form"))
                self.nbr_etoile.setText(_translate("saison_4", "TextLabel"))
                self.quit.setText(_translate("saison_4", "Quitter"))
                self.niv_5.setText(_translate("saison_4", "Niveau 5"))
                self.nom_joueur.setText(_translate("saison_4", "TextLabel"))
                self.niv_4.setText(_translate("saison_4", "Niveau 4"))
                self.save.setText(_translate("saison_4", "Sauvegarder"))
                self.niv_3.setText(_translate("saison_4", "Niveau 3"))
                self.niv_2.setText(_translate("saison_4", "Niveau 2"))
                self.sais_prec.setText(_translate("saison_4", "Monde precedent"))
                self.niv_1.setText(_translate("saison_4", "Niveau 1"))

        def griserEtoiles(self):
                """
                @brief Grise toutes les étoiles.

                @return Liste des groupes d'étoiles grises.
                @rtype list
                """
                grpEtoile = []
                for i in [self.etoile_1,self.etoile_2,self.etoile_3,self.etoile_4,self.etoile_5]:
                        self.disable(i)
                        grpEtoile.append(i)

                return grpEtoile

        def disable(self,liste):
                """
                @brief Désactive les éléments de la liste.

                @param liste Liste d'éléments à désactiver.
                @type liste list
                """
                for i in liste:
                        i.setEnabled(False)

        def updateStars(self,listeStars):
                """
                @brief Met à jour l'affichage des étoiles en fonction de la liste fournie.

                @param listeStars Liste du nombre d'étoiles pour chaque groupe.
                @type listeStars list
                """
                for i in range(5):
                        liste = self.grpEtoile[i]
                        for j in range(int(listeStars[i])):
                                liste[j].setEnabled(True)

        def changeColor(self,nivComplet):
                """
                @brief Change la couleur des boutons de niveau en fonction de la complétion.

                @param nivComplet Liste de complétion pour chaque niveau.
                @type nivComplet list
                """
                for i in range(5):
                        cpl = nivComplet[i]
                        if(cpl == "Y"):
                                self.button_niv[i].setStyleSheet("QPushButton{ background-color: green;}")

        def showHintBubble(self, event):
                """
                @brief Affiche une bulle d'indice lorsque l'image est cliquée.

                @param event Événement de clic de la souris.
                @type event PyQt5.QtCore.QEvent
                """
                self.popup = BottomPopup.BottomPopup(0, 4, 0, "pink",True)
                self.popup.show()