# -*- coding: utf-8 -*-

"""
@file saison_1.py
@brief Fichier de définition de la classe Ui_saison_1
"""

# Form implementation generated from reading ui file '.\ressource\saison1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MAIN import main
from POPUP import BottomPopup
import ressources


class Ui_saison_1(object):
        """
        @class Ui_saison_1
        @brief Classe définissant l'interface utilisateur de la saison 1
        """


        def setupUi(self, saison_1):
                """
                @brief Configurer l'interface utilisateur de la saison 1.

                @param saison_1 Fenêtre de la saison 1
                @type saison_1 QtWidgets.QWidget
                """

                ## Mise en place des ratios pour adapter les objets a la taille de l'ecran
                self.ratioHeight = main.ratio_size(1080,1)
                self.ratioWidth = main.ratio_size(1920,0)

                fontButtonNiv = QtGui.QFont()
                fontButtonNiv.setPointSize(15)

                fontButtonMenu = QtGui.QFont()
                fontButtonMenu.setPointSize(10)

                saison_1.setObjectName("saison_1")
                saison_1.resize(1920, 1080)

                ##Feuille de style
                saison_1.setStyleSheet("QWidget#saison_1{\n"
                                       "    background-image: url(:/img/fond/ete.png);\n"
                                       "    background-repeat: no-repeat;\n"
                                       "    background-position: center;\n"
                                       "    background-attachment: fixed;\n"
                                       "    background-size: cover;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton{\n"
                                       "    background-color: red;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton#sais_suiv{\n"
                                       "    background-color: grey;\n"
                                       "}\n"
                                       "QPushButton#save{\n"
                                       "    background-color: grey;\n"
                                       "}\n"
                                       "QPushButton#quit{\n"
                                       "    background-color: grey;\n"
                                       "}\n")

                ##Creation des boutons
                self.niv_5 = QtWidgets.QPushButton(saison_1)
                self.niv_5.setGeometry(main.creatRect(730,130,101,61,self.ratioWidth,self.ratioHeight))
                self.niv_5.setFont(fontButtonNiv)
                self.niv_5.setObjectName("niv_5")
                self.niv_4 = QtWidgets.QPushButton(saison_1)
                self.niv_4.setEnabled(True)
                self.niv_4.setGeometry(main.creatRect(960,330,101,61,self.ratioWidth,self.ratioHeight))
                self.niv_4.setFont(fontButtonNiv)
                self.niv_4.setObjectName("niv_4")
                self.niv_3 = QtWidgets.QPushButton(saison_1)
                self.niv_3.setGeometry(main.creatRect(760,510,101,61,self.ratioWidth,self.ratioHeight))
                self.niv_3.setFont(fontButtonNiv)
                self.niv_3.setObjectName("niv_3")
                self.niv_2 = QtWidgets.QPushButton(saison_1)
                self.niv_2.setGeometry(main.creatRect(1020,730,101,61,self.ratioWidth,self.ratioHeight))
                self.niv_2.setFont(fontButtonNiv)
                self.niv_2.setObjectName("niv_2")
                self.niv_1 = QtWidgets.QPushButton(saison_1)
                self.niv_1.setGeometry(main.creatRect(690,990,101,61,self.ratioWidth,self.ratioHeight))
                self.niv_1.setFont(fontButtonNiv)
                self.niv_1.setObjectName("niv_1")

                self.button_niv = []
                self.button_niv.append(self.niv_1)
                self.button_niv.append(self.niv_2)
                self.button_niv.append(self.niv_3)
                self.button_niv.append(self.niv_4)
                self.button_niv.append(self.niv_5)

                ##Etoile Niveau 1
                self.e_1_2 = QtWidgets.QLabel(saison_1)
                self.e_1_2.setGeometry(main.creatRect(668,930,51,51,self.ratioWidth,self.ratioHeight))
                self.e_1_2.setText("")
                self.e_1_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_2.setObjectName("e_1_2")
                self.e_1_3 = QtWidgets.QLabel(saison_1)
                self.e_1_3.setGeometry(main.creatRect(719,930,51,51,self.ratioWidth,self.ratioHeight))
                self.e_1_3.setText("")
                self.e_1_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_3.setObjectName("e_1_3")
                self.e_1_1 = QtWidgets.QLabel(saison_1)
                self.e_1_1.setGeometry(main.creatRect(617,930,51,51,self.ratioWidth,self.ratioHeight))
                self.e_1_1.setText("")
                self.e_1_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_1.setObjectName("e_1_1")
                self.e_1_5 = QtWidgets.QLabel(saison_1)
                self.e_1_5.setGeometry(main.creatRect(821,930,51,51,self.ratioWidth,self.ratioHeight))
                self.e_1_5.setText("")
                self.e_1_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_5.setObjectName("e_1_5")
                self.e_1_4 = QtWidgets.QLabel(saison_1)
                self.e_1_4.setGeometry(main.creatRect(770,930,51,51,self.ratioWidth,self.ratioHeight))
                self.e_1_4.setText("")
                self.e_1_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_4.setObjectName("e_1_4")

                self.etoile_1 = []
                self.etoile_1.append(self.e_1_1)
                self.etoile_1.append(self.e_1_2)
                self.etoile_1.append(self.e_1_3)
                self.etoile_1.append(self.e_1_4)
                self.etoile_1.append(self.e_1_5)

                ##Etoile Niveau 2
                self.e_2_1 = QtWidgets.QLabel(saison_1)
                self.e_2_1.setGeometry(main.creatRect(946,670,51,51,self.ratioWidth,self.ratioHeight))
                self.e_2_1.setText("")
                self.e_2_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_1.setObjectName("e_2_1")
                self.e_2_2 = QtWidgets.QLabel(saison_1)
                self.e_2_2.setGeometry(main.creatRect(997,670,51,51,self.ratioWidth,self.ratioHeight))
                self.e_2_2.setText("")
                self.e_2_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_2.setObjectName("e_2_2")
                self.e_2_4 = QtWidgets.QLabel(saison_1)
                self.e_2_4.setGeometry(main.creatRect(1099,670,51,51,self.ratioWidth,self.ratioHeight))
                self.e_2_4.setText("")
                self.e_2_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_4.setObjectName("e_2_4")
                self.e_2_3 = QtWidgets.QLabel(saison_1)
                self.e_2_3.setGeometry(main.creatRect(1048,670,51,51,self.ratioWidth,self.ratioHeight))
                self.e_2_3.setText("")
                self.e_2_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_3.setObjectName("e_2_3")
                self.e_2_5 = QtWidgets.QLabel(saison_1)
                self.e_2_5.setGeometry(main.creatRect(1150,670,51,51,self.ratioWidth,self.ratioHeight))
                self.e_2_5.setText("")
                self.e_2_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_5.setObjectName("e_2_5")

                self.etoile_2 = []
                self.etoile_2.append(self.e_2_1)
                self.etoile_2.append(self.e_2_2)
                self.etoile_2.append(self.e_2_3)
                self.etoile_2.append(self.e_2_4)
                self.etoile_2.append(self.e_2_5)

                ##Etoile Niveau 3
                self.e_3_4 = QtWidgets.QLabel(saison_1)
                self.e_3_4.setGeometry(main.creatRect(832,450,51,51,self.ratioWidth,self.ratioHeight))
                self.e_3_4.setText("")
                self.e_3_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_4.setObjectName("e_3_4")
                self.e_3_5 = QtWidgets.QLabel(saison_1)
                self.e_3_5.setGeometry(main.creatRect(883,450,51,51,self.ratioWidth,self.ratioHeight))
                self.e_3_5.setText("")
                self.e_3_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_5.setObjectName("e_3_5")
                self.e_3_3 = QtWidgets.QLabel(saison_1)
                self.e_3_3.setGeometry(main.creatRect(781,450,51,51,self.ratioWidth,self.ratioHeight))
                self.e_3_3.setText("")
                self.e_3_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_3.setObjectName("e_3_3")
                self.e_3_1 = QtWidgets.QLabel(saison_1)
                self.e_3_1.setGeometry(main.creatRect(679,450,51,51,self.ratioWidth,self.ratioHeight))
                self.e_3_1.setText("")
                self.e_3_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_1.setObjectName("e_3_1")
                self.e_3_2 = QtWidgets.QLabel(saison_1)
                self.e_3_2.setGeometry(main.creatRect(730,450,51,51,self.ratioWidth,self.ratioHeight))
                self.e_3_2.setText("")
                self.e_3_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_2.setObjectName("e_3_2")

                self.etoile_3 = []
                self.etoile_3.append(self.e_3_1)
                self.etoile_3.append(self.e_3_2)
                self.etoile_3.append(self.e_3_3)
                self.etoile_3.append(self.e_3_4)
                self.etoile_3.append(self.e_3_5)

                ##Etoile Niveau 4
                self.e_4_4 = QtWidgets.QLabel(saison_1)
                self.e_4_4.setGeometry(main.creatRect(1032,270,51,51,self.ratioWidth,self.ratioHeight))
                self.e_4_4.setText("")
                self.e_4_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_4.setObjectName("e_4_4")
                self.e_4_5 = QtWidgets.QLabel(saison_1)
                self.e_4_5.setGeometry(main.creatRect(1083,270,51,51,self.ratioWidth,self.ratioHeight))
                self.e_4_5.setText("")
                self.e_4_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_5.setObjectName("e_4_5")
                self.e_4_3 = QtWidgets.QLabel(saison_1)
                self.e_4_3.setGeometry(main.creatRect(981,270,51,51,self.ratioWidth,self.ratioHeight))
                self.e_4_3.setText("")
                self.e_4_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_3.setObjectName("e_4_3")
                self.e_4_1 = QtWidgets.QLabel(saison_1)
                self.e_4_1.setGeometry(main.creatRect(879,270,51,51,self.ratioWidth,self.ratioHeight))
                self.e_4_1.setText("")
                self.e_4_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_1.setObjectName("e_4_1")
                self.e_4_2 = QtWidgets.QLabel(saison_1)
                self.e_4_2.setGeometry(main.creatRect(930,270,51,51,self.ratioWidth,self.ratioHeight))
                self.e_4_2.setText("")
                self.e_4_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_2.setObjectName("e_4_2")

                self.etoile_4 = []
                self.etoile_4.append(self.e_4_1)
                self.etoile_4.append(self.e_4_2)
                self.etoile_4.append(self.e_4_3)
                self.etoile_4.append(self.e_4_4)
                self.etoile_4.append(self.e_4_5)

                ##Etoile Niveau 5
                self.e_5_4 = QtWidgets.QLabel(saison_1)
                self.e_5_4.setGeometry(main.creatRect(802,70,51,51,self.ratioWidth,self.ratioHeight))
                self.e_5_4.setText("")
                self.e_5_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_4.setObjectName("e_5_4")
                self.e_5_5 = QtWidgets.QLabel(saison_1)
                self.e_5_5.setGeometry(main.creatRect(853,70,51,51,self.ratioWidth,self.ratioHeight))
                self.e_5_5.setText("")
                self.e_5_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_5.setObjectName("e_5_5")
                self.e_5_3 = QtWidgets.QLabel(saison_1)
                self.e_5_3.setGeometry(main.creatRect(751,70,51,51,self.ratioWidth,self.ratioHeight))
                self.e_5_3.setText("")
                self.e_5_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_3.setObjectName("e_5_3")
                self.e_5_1 = QtWidgets.QLabel(saison_1)
                self.e_5_1.setGeometry(main.creatRect(649,70,51,51,self.ratioWidth,self.ratioHeight))
                self.e_5_1.setText("")
                self.e_5_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_1.setObjectName("e_5_1")
                self.e_5_2 = QtWidgets.QLabel(saison_1)
                self.e_5_2.setGeometry(main.creatRect(700,70,51,51,self.ratioWidth,self.ratioHeight))
                self.e_5_2.setText("")
                self.e_5_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_2.setObjectName("e_5_2")

                self.etoile_5 = []
                self.etoile_5.append(self.e_5_1)
                self.etoile_5.append(self.e_5_2)
                self.etoile_5.append(self.e_5_3)
                self.etoile_5.append(self.e_5_4)
                self.etoile_5.append(self.e_5_5)

                ##Aide pour le joueur
                self.helper = QtWidgets.QLabel(saison_1)
                self.helper.setGeometry(main.creatRect(1270,630,151,121,self.ratioWidth,self.ratioHeight))
                self.helper.setText("")
                self.helper.setPixmap(QtGui.QPixmap(":/img/perso/petit-helper.png"))
                self.helper.setObjectName("helper")
                self.helper.setToolTip("Indice")
                # Connecter le clic sur l'image à la fonction pour afficher la bulle de discussion
                self.helper.mousePressEvent = self.showHintBubble

                self.sais_suiv = QtWidgets.QPushButton(saison_1)
                self.sais_suiv.setGeometry(main.creatRect(890,10,141,41,self.ratioWidth,self.ratioHeight))
                self.sais_suiv.setObjectName("sais_suiv")
                self.sais_suiv.setFont(fontButtonMenu)

                self.nom_joueur = QtWidgets.QLabel(saison_1)
                self.nom_joueur.setGeometry(main.creatRect(20,10,371,81,self.ratioWidth,self.ratioHeight))
                font = QtGui.QFont()
                font.setPointSize(30)
                self.nom_joueur.setFont(font)
                self.nom_joueur.setObjectName("nom_joueur")

                self.nbr_e_img = QtWidgets.QLabel(saison_1)
                self.nbr_e_img.setGeometry(main.creatRect(40,70,51,51,self.ratioWidth,self.ratioHeight))
                self.nbr_e_img.setText("")
                self.nbr_e_img.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.nbr_e_img.setObjectName("nbr_e_img")

                self.nbr_etoile = QtWidgets.QLabel(saison_1)
                self.nbr_etoile.setGeometry(main.creatRect(100,70,121,61,self.ratioWidth,self.ratioHeight))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.nbr_etoile.setFont(font)
                self.nbr_etoile.setObjectName("nbr_etoile")

                self.quit = QtWidgets.QPushButton(saison_1)
                self.quit.setGeometry(main.creatRect(1770,1010,121,41,self.ratioWidth,self.ratioHeight))
                self.quit.setObjectName("quit")
                self.quit.setFont(fontButtonMenu)

                self.save = QtWidgets.QPushButton(saison_1)
                self.save.setGeometry(main.creatRect(1620,1010,121,41,self.ratioWidth,self.ratioHeight))
                self.save.setObjectName("save")
                self.save.setFont(fontButtonMenu)

                self.retranslateUi(saison_1)
                QtCore.QMetaObject.connectSlotsByName(saison_1)

                self.widget = saison_1
                self.grpEtoile = self.griserEtoiles()

        def retranslateUi(self, saison_1):
                """
                @brief Retraduire les éléments de l'interface utilisateur de la saison 1.

                @param saison_1 Fenêtre de la saison 1
                @type saison_1 QtWidgets.QWidget
                """
                _translate = QtCore.QCoreApplication.translate

                saison_1.setWindowTitle(_translate("saison_1", "Form"))
                self.niv_5.setText(_translate("saison_1", "Niveau 5"))
                self.niv_4.setText(_translate("saison_1", "Niveau 4"))
                self.niv_3.setText(_translate("saison_1", "Niveau 3"))
                self.niv_2.setText(_translate("saison_1", "Niveau 2"))
                self.niv_1.setText(_translate("saison_1", "Niveau 1"))

                self.sais_suiv.setText(_translate("saison_1", "Monde suivant"))

                self.nom_joueur.setText(_translate("saison_1", "TextLabel"))

                self.nbr_etoile.setText(_translate("saison_1", "TextLabel"))

                self.quit.setText(_translate("saison_1", "Quitter"))
                self.save.setText(_translate("saison_1", "Sauvegarder"))

        def griserEtoiles(self):
                """
                @brief Griser toutes les étoiles.

                @return Liste des groupes d'étoiles
                @rtype list
                """
                grpEtoile = []
                for i in [self.etoile_1,self.etoile_2,self.etoile_3,self.etoile_4,self.etoile_5]:
                        self.disable(i)
                        grpEtoile.append(i)

                return grpEtoile

        def disable(self,liste):
                """
                @brief Désactiver tous les éléments de la liste.

                @param liste Liste d'éléments à désactiver
                @type liste list
                """
                for i in liste:
                        i.setEnabled(False)

        def updateStars(self,listeStars):
                """
                @brief Mettre à jour l'affichage des étoiles en fonction de la liste fournie.

                @param listeStars Liste du nombre d'étoiles pour chaque niveau
                @type listeStars list
                """
                for i in range(5):
                        liste = self.grpEtoile[i]
                        for j in range(int(listeStars[i])):
                                liste[j].setEnabled(True)

        def changeColor(self,nivComplet):
                """
                @brief Changer la couleur des boutons de niveau en fonction de la complétion.

                @param nivComplet Liste de la complétion de chaque niveau
                @type nivComplet list
                """
                for i in range(5):
                        cpl = nivComplet[i]
                        if(cpl == "Y"):
                                self.button_niv[i].setStyleSheet("QPushButton{ background-color: green;}")

        # Fonction pour afficher la bulle de discussion de Helper
        def showHintBubble(self, event):
                """
                @brief Afficher la bulle de discussion de l'assistant (Helper).

                @param event Événement de clic de la souris
                @type event PyQt5.QtCore.QEvent
                """
                # Création d'une fenêtre modale personnalisée avec QMessageBox
                self.popup = BottomPopup.BottomPopup(0, 1, 0, "green", True)
                self.popup.show()