# -*- coding: utf-8 -*-

"""
@file saison_2.py
@brief Fichier de définition de la classe Ui_saison_2
"""

# Form implementation generated from reading ui file './ressource/saison2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MAIN import main
from POPUP import BottomPopup
import ressources


class Ui_saison_2(object):
        """
        @class Ui_saison_2
        @brief Classe définissant l'interface utilisateur de la saison 2
        """

        def setupUi(self, saison_2):
                """
                @brief Configure l'interface utilisateur.

                @param saison_2 Le widget principal de l'interface.
                @type saison_2 QtWidgets.QWidget
                """

                self.ratioHeight = main.ratio_size(1080, 1)
                self.ratioWidth = main.ratio_size(1920, 0)

                saison_2.setObjectName("saison_2")
                saison_2.resize(1920, 1080)
                saison_2.setStyleSheet("QWidget#saison_2{\n"
                "    background-image: url(:/img/fond/automne.png);\n"
                "    background-repeat: no-repeat;\n"
                "    background-position: center;\n"
                "    background-attachment: fixed;\n"
                "    background-size: cover;\n"
                "}\n"
                "QPushButton{\n"
                "    background-color: red;\n"
                "}\n"
                "\n"
                "QPushButton#sais_suiv{\n"
                "    background-color: grey;\n"
                "}\n"
                "QPushButton#sais_prec{\n"
                "    background-color: grey;\n"
                "}\n"
                "QPushButton#save{\n"
                "    background-color: grey;\n"
                "}\n"
                "QPushButton#quit{\n"
                "    background-color: grey;\n"
                "}")

                fontButtonNiv = QtGui.QFont()
                fontButtonNiv.setPointSize(15)

                fontButtonMenu = QtGui.QFont()
                fontButtonMenu.setPointSize(10)

                self.e_1_1 = QtWidgets.QLabel(saison_2)
                self.e_1_1.setGeometry(main.creatRect(767, 810, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_1_1.setText("")
                self.e_1_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_1.setObjectName("e_1_1")
                self.niv_1 = QtWidgets.QPushButton(saison_2)
                self.niv_1.setGeometry(main.creatRect(840, 870, 101, 61,self.ratioWidth,self.ratioHeight))
                self.niv_1.setObjectName("niv_1")
                self.niv_1.setFont(fontButtonNiv)
                self.e_1_2 = QtWidgets.QLabel(saison_2)
                self.e_1_2.setGeometry(main.creatRect(818, 810, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_1_2.setText("")
                self.e_1_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_2.setObjectName("e_1_2")
                self.e_1_3 = QtWidgets.QLabel(saison_2)
                self.e_1_3.setGeometry(main.creatRect(869, 810, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_1_3.setText("")
                self.e_1_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_3.setObjectName("e_1_3")
                self.e_1_5 = QtWidgets.QLabel(saison_2)
                self.e_1_5.setGeometry(main.creatRect(971, 810, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_1_5.setText("")
                self.e_1_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_5.setObjectName("e_1_5")
                self.e_1_4 = QtWidgets.QLabel(saison_2)
                self.e_1_4.setGeometry(main.creatRect(920, 810, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_1_4.setText("")
                self.e_1_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_1_4.setObjectName("e_1_4")
                self.niv_2 = QtWidgets.QPushButton(saison_2)
                self.niv_2.setGeometry(main.creatRect(622, 680, 101, 61,self.ratioWidth,self.ratioHeight))
                self.niv_2.setObjectName("niv_2")
                self.niv_2.setFont(fontButtonNiv)
                self.e_2_1 = QtWidgets.QLabel(saison_2)
                self.e_2_1.setGeometry(main.creatRect(548, 620, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_2_1.setText("")
                self.e_2_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_1.setObjectName("e_2_1")
                self.e_2_4 = QtWidgets.QLabel(saison_2)
                self.e_2_4.setGeometry(main.creatRect(701, 620, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_2_4.setText("")
                self.e_2_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_4.setObjectName("e_2_4")
                self.e_2_5 = QtWidgets.QLabel(saison_2)
                self.e_2_5.setGeometry(main.creatRect(752, 620, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_2_5.setText("")
                self.e_2_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_5.setObjectName("e_2_5")
                self.e_2_2 = QtWidgets.QLabel(saison_2)
                self.e_2_2.setGeometry(main.creatRect(599, 620, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_2_2.setText("")
                self.e_2_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_2.setObjectName("e_2_2")
                self.e_2_3 = QtWidgets.QLabel(saison_2)
                self.e_2_3.setGeometry(main.creatRect(650, 620, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_2_3.setText("")
                self.e_2_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_2_3.setObjectName("e_2_3")
                self.niv_3 = QtWidgets.QPushButton(saison_2)
                self.niv_3.setGeometry(main.creatRect(399, 490, 101, 61,self.ratioWidth,self.ratioHeight))
                self.niv_3.setObjectName("niv_3")
                self.niv_3.setFont(fontButtonNiv)
                self.e_3_2 = QtWidgets.QLabel(saison_2)
                self.e_3_2.setGeometry(main.creatRect(369, 430, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_3_2.setText("")
                self.e_3_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_2.setObjectName("e_3_2")
                self.e_3_5 = QtWidgets.QLabel(saison_2)
                self.e_3_5.setGeometry(main.creatRect(522, 430, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_3_5.setText("")
                self.e_3_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_5.setObjectName("e_3_5")
                self.e_3_4 = QtWidgets.QLabel(saison_2)
                self.e_3_4.setGeometry(main.creatRect(471, 430, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_3_4.setText("")
                self.e_3_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_4.setObjectName("e_3_4")
                self.e_3_1 = QtWidgets.QLabel(saison_2)
                self.e_3_1.setGeometry(main.creatRect(318, 430, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_3_1.setText("")
                self.e_3_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_1.setObjectName("e_3_1")
                self.e_3_3 = QtWidgets.QLabel(saison_2)
                self.e_3_3.setGeometry(main.creatRect(420, 430, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_3_3.setText("")
                self.e_3_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_3_3.setObjectName("e_3_3")
                self.e_4_1 = QtWidgets.QLabel(saison_2)
                self.e_4_1.setGeometry(main.creatRect(737, 170, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_4_1.setText("")
                self.e_4_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_1.setObjectName("e_4_1")
                self.e_4_5 = QtWidgets.QLabel(saison_2)
                self.e_4_5.setGeometry(main.creatRect(941, 170, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_4_5.setText("")
                self.e_4_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_5.setObjectName("e_4_5")
                self.e_4_2 = QtWidgets.QLabel(saison_2)
                self.e_4_2.setGeometry(main.creatRect(788, 170, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_4_2.setText("")
                self.e_4_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_2.setObjectName("e_4_2")
                self.e_4_3 = QtWidgets.QLabel(saison_2)
                self.e_4_3.setGeometry(main.creatRect(839, 170, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_4_3.setText("")
                self.e_4_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_3.setObjectName("e_4_3")
                self.niv_4 = QtWidgets.QPushButton(saison_2)
                self.niv_4.setEnabled(True)
                self.niv_4.setGeometry(main.creatRect(818, 230, 101, 61,self.ratioWidth,self.ratioHeight))
                self.niv_4.setObjectName("niv_4")
                self.niv_4.setFont(fontButtonNiv)
                self.e_4_4 = QtWidgets.QLabel(saison_2)
                self.e_4_4.setGeometry(main.creatRect(890, 170, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_4_4.setText("")
                self.e_4_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_4_4.setObjectName("e_4_4")
                self.e_5_2 = QtWidgets.QLabel(saison_2)
                self.e_5_2.setGeometry(main.creatRect(1300, 40, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_5_2.setText("")
                self.e_5_2.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_2.setObjectName("e_5_2")
                self.e_5_5 = QtWidgets.QLabel(saison_2)
                self.e_5_5.setGeometry(main.creatRect(1453, 40, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_5_5.setText("")
                self.e_5_5.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_5.setObjectName("e_5_5")
                self.e_5_1 = QtWidgets.QLabel(saison_2)
                self.e_5_1.setGeometry(main.creatRect(1249, 40, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_5_1.setText("")
                self.e_5_1.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_1.setObjectName("e_5_1")
                self.e_5_4 = QtWidgets.QLabel(saison_2)
                self.e_5_4.setGeometry(main.creatRect(1402, 40, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_5_4.setText("")
                self.e_5_4.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_4.setObjectName("e_5_4")
                self.e_5_3 = QtWidgets.QLabel(saison_2)
                self.e_5_3.setGeometry(main.creatRect(1351, 40, 51, 51,self.ratioWidth,self.ratioHeight))
                self.e_5_3.setText("")
                self.e_5_3.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.e_5_3.setObjectName("e_5_3")
                self.niv_5 = QtWidgets.QPushButton(saison_2)
                self.niv_5.setGeometry(main.creatRect(1330, 100, 101, 61,self.ratioWidth,self.ratioHeight))
                self.niv_5.setObjectName("niv_5")
                self.niv_5.setFont(fontButtonNiv)
                self.sais_suiv = QtWidgets.QPushButton(saison_2)
                self.sais_suiv.setGeometry(main.creatRect(1620, 30, 141, 41,self.ratioWidth,self.ratioHeight))
                self.sais_suiv.setObjectName("sais_suiv")
                self.sais_suiv.setFont(fontButtonMenu)
                self.sais_prec = QtWidgets.QPushButton(saison_2)
                self.sais_prec.setGeometry(main.creatRect(560, 1015, 141, 41,self.ratioWidth,self.ratioHeight))
                self.sais_prec.setObjectName("sais_prec")
                self.sais_prec.setFont(fontButtonMenu)
                self.save = QtWidgets.QPushButton(saison_2)
                self.save.setGeometry(main.creatRect(1620, 1010, 121, 41,self.ratioWidth,self.ratioHeight))
                self.save.setObjectName("save")
                self.save.setFont(fontButtonMenu)
                self.quit = QtWidgets.QPushButton(saison_2)
                self.quit.setGeometry(main.creatRect(1770, 1010, 121, 41,self.ratioWidth,self.ratioHeight))
                self.quit.setObjectName("quit")
                self.quit.setFont(fontButtonMenu)
                self.nbr_e_img = QtWidgets.QLabel(saison_2)
                self.nbr_e_img.setGeometry(main.creatRect(40, 70, 51, 51,self.ratioWidth,self.ratioHeight))
                self.nbr_e_img.setText("")
                self.nbr_e_img.setPixmap(QtGui.QPixmap(":/img/star.png"))
                self.nbr_e_img.setObjectName("nbr_e_img")
                self.nbr_etoile = QtWidgets.QLabel(saison_2)
                self.nbr_etoile.setGeometry(main.creatRect(100, 70, 121, 61,self.ratioWidth,self.ratioHeight))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.nbr_etoile.setFont(font)
                self.nbr_etoile.setObjectName("nbr_etoile")
                self.nom_joueur = QtWidgets.QLabel(saison_2)
                self.nom_joueur.setGeometry(main.creatRect(20, 10, 371, 81,self.ratioWidth,self.ratioHeight))
                font = QtGui.QFont()
                font.setPointSize(30)
                self.nom_joueur.setFont(font)
                self.nom_joueur.setObjectName("nom_joueur")
                self.label = QtWidgets.QLabel(saison_2)
                self.label.setGeometry(main.creatRect(680, 340, 151, 121,self.ratioWidth,self.ratioHeight))
                self.label.setText("")
                self.label.setPixmap(QtGui.QPixmap(":/img/perso/petit-helper.png"))
                self.label.setObjectName("label")
                self.label.setToolTip("Indice")
                # Connecter le clic sur l'image à la fonction pour afficher la bulle de discussion
                self.label.mousePressEvent = self.showHintBubble

                self.retranslateUi(saison_2)
                QtCore.QMetaObject.connectSlotsByName(saison_2)

                self.widget = saison_2

                self.button_niv = []
                self.button_niv.append(self.niv_1)
                self.button_niv.append(self.niv_2)
                self.button_niv.append(self.niv_3)
                self.button_niv.append(self.niv_4)
                self.button_niv.append(self.niv_5)

                self.etoile_1 = []
                self.etoile_1.append(self.e_1_1)
                self.etoile_1.append(self.e_1_2)
                self.etoile_1.append(self.e_1_3)
                self.etoile_1.append(self.e_1_4)
                self.etoile_1.append(self.e_1_5)

                self.etoile_2 = []
                self.etoile_2.append(self.e_2_1)
                self.etoile_2.append(self.e_2_2)
                self.etoile_2.append(self.e_2_3)
                self.etoile_2.append(self.e_2_4)
                self.etoile_2.append(self.e_2_5)

                self.etoile_3 = []
                self.etoile_3.append(self.e_3_1)
                self.etoile_3.append(self.e_3_2)
                self.etoile_3.append(self.e_3_3)
                self.etoile_3.append(self.e_3_4)
                self.etoile_3.append(self.e_3_5)

                self.etoile_4 = []
                self.etoile_4.append(self.e_4_1)
                self.etoile_4.append(self.e_4_2)
                self.etoile_4.append(self.e_4_3)
                self.etoile_4.append(self.e_4_4)
                self.etoile_4.append(self.e_4_5)

                self.etoile_5 = []
                self.etoile_5.append(self.e_5_1)
                self.etoile_5.append(self.e_5_2)
                self.etoile_5.append(self.e_5_3)
                self.etoile_5.append(self.e_5_4)
                self.etoile_5.append(self.e_5_5)

                self.grpEtoile = self.griserEtoiles()

        def retranslateUi(self, saison_2):
                """
                @brief Traduit les composants de l'interface utilisateur.

                @param saison_2 Le widget principal de l'interface.
                @type saison_2 QtWidgets.QWidget
                """
                _translate = QtCore.QCoreApplication.translate
                saison_2.setWindowTitle(_translate("saison_2", "Form"))
                self.niv_1.setText(_translate("saison_2", "Niveau 1"))
                self.niv_2.setText(_translate("saison_2", "Niveau 2"))
                self.niv_3.setText(_translate("saison_2", "Niveau 3"))
                self.niv_4.setText(_translate("saison_2", "Niveau 4"))
                self.niv_5.setText(_translate("saison_2", "Niveau 5"))
                self.sais_suiv.setText(_translate("saison_2", "Monde suivant"))
                self.sais_prec.setText(_translate("saison_2", "Monde precedent"))
                self.save.setText(_translate("saison_2", "Sauvegarder"))
                self.quit.setText(_translate("saison_2", "Quitter"))
                self.nbr_etoile.setText(_translate("saison_2", "TextLabel"))
                self.nom_joueur.setText(_translate("saison_2", "TextLabel"))

        def griserEtoiles(self):
                """
                @brief Désactive tous les labels d'étoiles.

               @return Liste de listes contenant des objets QLabel pour les étoiles de chaque niveau.
               @rtype list
               """
                grpEtoile = []
                for i in [self.etoile_1,self.etoile_2,self.etoile_3,self.etoile_4,self.etoile_5]:
                        self.disable(i)
                        grpEtoile.append(i)

                return grpEtoile

        def disable(self,liste):
                """
                @brief Désactive une liste d'objets QLabel.

                @param liste Liste d'objets QLabel.
                @type liste list
                """
                for i in liste:
                        i.setEnabled(False)

        def updateStars(self,listeStars):
                """
                @brief Met à jour les labels d'étoiles en fonction du nombre d'étoiles fourni pour chaque niveau.

                @param listeStars Liste du nombre d'étoiles pour chaque niveau.
                @type listeStars list
                """
                for i in range(5):
                        liste = self.grpEtoile[i]
                        for j in range(int(listeStars[i])):
                                liste[j].setEnabled(True)

        def changeColor(self,nivComplet):
                """
                @brief Change la couleur des boutons de niveau en fonction de l'état de complétion.

                @param nivComplet Liste de l'état de complétion pour chaque niveau.
                @type nivComplet list
                """
                for i in range(5):
                        cpl = nivComplet[i]
                        if(cpl == "Y"):
                                self.button_niv[i].setStyleSheet("QPushButton{ background-color: green;}")

        def showHintBubble(self, event):
                """
                @brief Affiche une bulle d'indice lorsqu'on clique sur l'image d'indice.

                @param event Événement de souris déclenchant la fonction.
                @type event PyQt5.QtCore.QEvent
                """
                self.popup = BottomPopup.BottomPopup(0, 2, 0, "orange", True)
                self.popup.show()
